name: descent_randomizer
description: A descent monster randomizer.

dependencies:
  redux: ">=2.0.0 <3.0.0"
  flutter_redux: ">=0.3.0 <0.4.0"
  flutter:
    sdk: flutter

  quiver: '^0.24.0'
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  assets:
    - lib/assets/building.png
    - lib/assets/cave.png
    - lib/assets/civilized.png
    - lib/assets/cold.png
    - lib/assets/cursed.png
    - lib/assets/dark.png
    - lib/assets/hot.png
    - lib/assets/mountain.png
    - lib/assets/water.png
    - lib/assets/wilderness.png
    - lib/assets/plot_deck.png
    - lib/assets/overlord_deck.png
    - lib/assets/monster_cards.png
    - lib/assets/collection.png
    - lib/assets/shadow_of_nerekhall.png
    - lib/assets/chains_that_rust.png
    - lib/assets/base_set.png
    - lib/assets/lieutenants/splig.png
    - lib/assets/lieutenants/belthir.png
    - lib/assets/lieutenants/alric_farrow.png
    - lib/assets/lieutenants/merick_farrow.png
    - lib/assets/lieutenants/eliza_farrow.png
    - lib/assets/lieutenants/zachareth.png
    - lib/assets/lieutenants/valyndra.png
    - lib/assets/lieutenants/raythen.png
    - lib/assets/lieutenants/queen_ariad.png
    - lib/assets/lieutenants/bol_goreth.png
    - lib/assets/lieutenants/rylan_olliven.png
    - lib/assets/lieutenants/verminous.png
    - lib/assets/lieutenants/tristayne_olliven.png
    - lib/assets/lieutenants/gargane_mirklace.png
    - lib/assets/lieutenants/skarn.png
    - lib/assets/lieutenants/zarihell.png
    - lib/assets/lieutenants/ardus_ix_erebus.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. The `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
